// -------- START USERS REQUESTS -------- //
### REGISTER A USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "pseudonym": "raoakif08",
  "email": "akifrao8@gmail.com",
  "city": "Lahore",
  "password": "123456",
  "country": "Pakistan",
  "profileImage": "https://avatars.githubusercontent.com/u/61361037?s=400&u=5a3fe223b969f16e2a4523817eb3acf361935f74&v=4"
}

### LOGIN USER
POST http://localhost:5000/api/auth/
Content-Type: application/json

{
  "pseudonym": "raoakif",
  "password": "123456"
}

### GET ALL USERS
GET http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### GET USER BY ID
GET http://localhost:5000/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### EDIT USER
PUT http://localhost:5000/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
    "pseudonym": "raoakif",
    "email": "akifrao@gmail.com",
    "password": "123456",
    "profileImage": "https://raw.githubusercontent.com/Immages/writinghat/main/caps/thinking_cap1.png"
}

### DELETE A USER
DELETE http://localhost:5000/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA
// -------- END USERS REQUESTS -------- //

# ---------------------------------------------------------

// -------- START PROMPT-CATEGORY REQUESTS -------- //
### ADD A PROMT-CATEGORY
POST http://localhost:5000/api/promptCategories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
  "name": "cook"
}

### GET ALL PROMPT-CATEGORIES
GET http://localhost:5000/api/promptCategories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### GET PROMPT-CATEGORY BY ID
GET http://localhost:5000/api/promptCategories/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### EDIT PROMPT-CATEGORY BY ID
PUT http://localhost:5000/api/promptCategories/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
  "name": "cooking"
}

### DELETE PROMPT-CATEGORY BY ID
DELETE http://localhost:5000/api/promptCategories/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA
// -------- END PROMPT-CATEGORY REQUESTS -------- //

# ---------------------------------------------------------

// -------- START PROMPT REQUESTS -------- //
### ADD A PROMT
POST http://localhost:5000/api/prompts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
  "title": "No Nonsense",
  "description": "Finally someone showed up with a glass of water! Sue frantically leaped towards the fisherman and finally someone showed up with a glass of water!",
  "promptCategoryId": 1,
  "userId": 1
}

# {
#   "title": "Sleep Hollow",
#   "description": "No other sounds were ever heard from the basement anymore. They always wondered if no other sounds were ever heard from the basement anymore.",
#   "promptCategoryId": 2,
#   "userId": 2
# }


### GET ALL PROMPT
GET http://localhost:5000/api/prompts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### GET PROMPT BY ID
GET http://localhost:5000/api/prompts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### EDIT PROMPT BY ID
PUT http://localhost:5000/api/prompts/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
  "title": "No Nonsense",
  "description": "Finally someone showed up with a glass of water! They always wondered if the ghost had finally  dissappeared from the house. No other sounds were ever heard from the dusty basement anymore. They always would wonder if the ghost had finally left and dissappeared from the house.They always  wondered if the ghost had finally  dissappeared from the house. They always  wondered if the ghost had finally  dissappeared from the house. I They always  wondered if the ghost had finally  dissappeared from the house.",
  "promptId": 2,
  "userId": 2
}

### DELETE PROMPT BY ID
DELETE http://localhost:5000/api/prompts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjY4MjkyNSwiZXhwIjoxNjgzMjg3NzI1fQ.VwNnGalQknXpX-tR3DNaoA0yQhZDsEqYcX_dGLFxG1g
// -------- END PROMPT REQUESTS -------- //

# ---------------------------------------------------------

// -------- START RESPONSE REQUESTS -------- //
### ADD A RESPONSE
POST http://localhost:5000/api/responses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
  "title": "Sleep Hollow",
  "description": "No other sounds were ever heard from the basement anymore. They always wondered if no other sounds were ever heard from the basement anymore.",
  "userId": 1,
  "promptId": 1
}

### GET ALL RESPONSES
GET http://localhost:5000/api/responses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### GET RESPONSE BY ID
GET http://localhost:5000/api/responses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### EDIT RESPONSES BY ID
PUT http://localhost:5000/api/responses/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
  "id": 6,
  "title": "No Nonsense",
  "description": "Finally someone showed up with a glass of water! They always wondered if the ghost had finally  dissappeared from the house. No other sounds were ever heard from the dusty basement anymore. They always would wonder if the ghost had finally left and dissappeared from the house.They always  wondered if the ghost had finally  dissappeared from the house. They always  wondered if the ghost had finally  dissappeared from the house. I They always  wondered if the ghost had finally  dissappeared from the house.",
  "promptId": 1,
  "userId": 2
}

### DELETE RESPONSE BY ID
DELETE http://localhost:5000/api/responses/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

// -------- END RESPONSE REQUESTS -------- //


### LOGIN USER
POST https://writing-hat-api.vercel.app/api/auth/
Content-Type: application/json

{
  "pseudonym": "raoakif",
  "password": "123456"
}


### GET ALL USERS
GET https://writing-hat-api.vercel.app/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjY4MjkyNSwiZXhwIjoxNjgzMjg3NzI1fQ.VwNnGalQknXpX-tR3DNaoA0yQhZDsEqYcX_dGLFxG1g

### GET ALL PROMPTS
GET https://writing-hat-api.vercel.app/api/prompts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjY4MjkyNSwiZXhwIjoxNjgzMjg3NzI1fQ.VwNnGalQknXpX-tR3DNaoA0yQhZDsEqYcX_dGLFxG1g

### EDIT PROMPT BY ID
PUT https://writing-hat-api.vercel.app/api/prompts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjY4MjkyNSwiZXhwIjoxNjgzMjg3NzI1fQ.VwNnGalQknXpX-tR3DNaoA0yQhZDsEqYcX_dGLFxG1g

{
  "description": "Leisure by William Henry Davies",
  "promptCategoryId": 2,
  "userId": 1
}